### ISSUE TITLE
Peer connections are not closed after peer destroy

### ISSUE THREAD

**Issue by katekbg** [nttcom/SkyWay-iOS-SDK#4]
Test Environment:
iOS SDK v.0.2.1 and iOS SDK v.0.2.2
iOS 9.3
iPhone 5s
Remote Port: 3000

In our project, there should only be 3 established connections to remote port.
1. Socket 
2. Peer
3. MediaConnection

Peer connections are not closed but accumulate in CloseWait state after calling `destroy` with peer.

![peer_connections](https://cloud.githubusercontent.com/assets/12931062/18902553/4e2d906e-8586-11e6-99d7-65d3937e975c.png)

As you can see in the attached image, the previous connections are still active in CloseWait state. It accumulates every time we establish a new connection even when `destroy` is called before establishing the new connection.

Is this an existing issue with the SDK? Or is it just in our side?

**Comment by tsu-takahashi** [comment]
Hi,

Our SkyWay SDK currently doesn’t use the destination port 3000/TCP.
  2. Peer —> HTTPS/TCP connection to skyway.io
  3. MediaConnection —> UDP or TURN-TCP

So please check if your TCP connections, established with your own server or remote-peer, are closed correctly.

Best regards,
